version: 2

models:
  - name: dim_products
    description: product info including price, inventory, and total ordered historically.
    columns:
      - name: product_guid
        tests:
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: price_usd
        tests:
          - positive_values
      - name: inventory_qty
        tests:
          - positive_values
      - name: total_ordered
        tests:
          - positive_values


  - name: dim_users
    description: general user information, contact info, and first and last order dates.
    columns:
      - name: user_guid
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: address
        tests:
          - not_null    
      - name: state
        tests:
      - name: zipcode
        tests:
      - name: country
        tests:
          - not_null
      - name: phone_number
        tests:
      - name: user_email
        tests:
          - not_null
      - name: created_at_utc
        tests:
          - not_null
      - name: first_order
        tests:
      - name: latest_order
        tests:


  - name: fct_orders
    description: order data including who placed the order, order/delivery dates, hours to deliver, promo codes, and country.
    columns:
      - name: order_guid
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: user_email
        tests:
          - not_null    
      - name: order_total_cost
        tests:
          - positive_values
      - name: item_count
        tests:
          - positive_values
      - name: created_at_utc
        tests:
          - not_null
      - name: estimated_delivery_at_utc
        tests:
      - name: delivered_at_utc
        tests:
      - name: hours_to_deliver
        tests:
      - name: order_status
        tests:
          - not_null
      - name: promo_type
        tests:
      - name: country
        tests:
          - not_null