version: 2

models:
  - name: int_session_events_agg
    description: indicates which type of events occurred within each session
    columns:
      - name: session_guid
        tests:
          - not_null
          - unique
      - name: user_guid
        tests:
          - not_null
      - name: created_at_utc
        tests:
          - not_null
      - name: add_to_cart
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: checkout
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: page_view
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: package_shipped
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false

  - name: int_session_length
    description: Returns the start and end of each session and calculates session length in minutes.
    columns:
      - name: session_guid
        tests:
          - not_null
          - unique
      - name: first_event
        tests:
          - not_null
      - name: last_event
        tests:
          - not_null
      - name: session_length_minutes
        tests:
          - positive_values    