version: 2

models:
  - name: stg_greenery__addresses
    description: user street addresses, including address, state, zip, etc.
    columns:
      - name: address_guid
        tests:
          - not_null
      - name: address
        tests:
          - not_null
      - name: zipcode
        tests:
      - name: state
        tests:
      - name: country
        tests:

  - name: stg_greenery__events
    description: events from webpage, including associated url, user, order, and product(s) as applicable
    columns:
      - name: event_guid
        tests:
          - not_null
      - name: session_guid
        tests:
      - name: user_guid
        tests:
      - name: page_url
        tests:
      - name: created_at_utc
        tests:
      - name: event_type
        tests:
      - name: order_guid
        tests:
      - name: product_guid
        tests:

  - name: stg_greenery__order_items
    description: items which have been ordered
    columns: 
      - name: order_guid
        tests:
          - not_null
      - name: product_guid
        tests:
          - not_null
      - name: quantity
        tests:
          - positive_values

  - name: stg_greenery__orders
    description: user orders including cost, shipping, order status and delivery details
    columns:
      - name: order_guid
        tests:
          - not_null
      - name: user_guid
        tests:
          - not_null
      - name: promo_type
        tests:
      - name: address_guid
        tests:
          - not_null
      - name: created_at_utc
        tests:
      - name: order_cost
        tests:
      - name: shipping_cost
        tests:
      - name: order_total_cost
        tests:
      - name: tracking_guid
        tests:
      - name: shipping_service
        tests:
      - name: estimated_delivery_utc
        tests:
      - name: delivered_at_utc
        tests:
      - name: order_status
        tests:

  - name: stg_greenery__products
    description: product list, including name, price and inventory
    columns:  
      - name: product_guid
        tests:
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: price_usd
        tests:
          - positive_values
      - name: inventory_qty
        tests:
          - positive_values

  - name: stg_greenery__promos
    description: current and past promos/discounts and status information
    columns:
      - name: promo_type
        tests:
          - not_null
      - name: discount
        tests:
          - positive_values
      - name: promo_status
        tests:
          - not_null

  - name: stg_greenery__users
    description: user names and contact information, including creation and update timestamps
    columns:
      - name: user_guid
        tests:
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: user_email
        tests:
          - not_null
      - name: phone_number
        tests:  
          - not_null
      - name: created_at_utc
        tests:
          - not_null
      - name: updated_at_utc
        tests:
          - not_null
      - name: address_guid
        tests:
          - not_null
      