version: 2

models:
  - name: fct_product_events
    description: Aggregates each product's session events by type, unique orders, unique sessions, and conversion rate.
    columns:
      - name: product_guid
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
      - name: unique_sessions
        tests:
      - name: unique_orders
        tests:
      - name: total_add_to_cart_events
        tests:
      - name: total_checkout_events
        tests:
      - name: total_page_view_events
        tests:
      - name: total_package_shipped_events
        tests:
      - name: product_conversion_rate
        tests:
          - positive_values


  - name: fct_sessions
    description: source of truth for each session, including user, events, start/end, and session length.
    columns:
      - name: session_guid
        tests:
          - not_null
          - unique
      - name: user_guid
        tests:
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: user_email
        tests:
          - not_null
      - name: page_view
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: add_to_cart
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: checkout
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: package_shipped
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false
      - name: first_event
        tests:
          - not_null
      - name: last_event
        tests:
          - not_null
      - name: session_length_minutes
        tests:
          - positive_values